### ISSUE TITLE
[Feature Request] `ConfigModel.it`: semantic alternative to `create(...)`

### ISSUE THREAD

**Issue by GreyElaina** [GraiaProject/kayaku#5]
```py
ConfigModel.it(cls: type[Self]) -> Self
# equal to
from kayaku import create

conf = create(Model)
```

**Comment by BlueGlassBlock** [comment]
为什么我感觉 `model.it` 在语义上不是很 make sense 的样子

**Comment by GreyElaina** [comment]
> 为什么我感觉 `model.it` 在语义上不是很 make sense 的样子

这个是引用来自 `creart.it` 的。

**Comment by BlueGlassBlock** [comment]
`creart.it` 可以解释成 `create it`，那 `model.it` 呢..?

**Comment by GreyElaina** [comment]
> `creart.it` 可以解释成 `create it`，那 `model.it` 呢..?

我的本意是 “引用这个配置”，不过你有更好的命名吗？

**Comment by BlueGlassBlock** [comment]
`dataclass_transform` 似乎不是很喜欢这样玩
